server:
  port: 8989
  context-path: /cmfz
  jsp-servlet:
    init-parameters:
      develoment: true
spring:
  datasource:
    username: hr
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:@localhost:1521:xe
  mvc:
    view:
      suffix: .jsp
      prefix: /
  http:
    encoding:
      charset: UTF-8
      force: true
mybatis:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:/com/baizhi/mapper/*.xml